######################################################################
# Automatically generated by qmake (2.01a) Sa. Mai 10 07:29:55 2014
######################################################################

TEMPLATE = subdirs

# Directories

#INCLUDEPATH += src/include/ \
#	rtosc/include

# Input

#HEADERS += src/

SOURCES += src/main.cpp
#    src/include/effect.cpp

OTHER_FILES += INSTALL.txt \
	README.txt \
	CMakeLists.txt


