######################################################################
# Automatically generated by qmake (2.01a) Sa. Mai 10 07:29:55 2014
######################################################################

TEMPLATE = subdirs

# Directories

#INCLUDEPATH += src/include/ \
#	rtosc/include

# Input

HEADERS += src/lo_server.h \
	src/grid.h

SOURCES += src/main.cpp \
	src/lo_server.cpp \
	src/grid.cpp

OTHER_FILES += INSTALL.txt \
	README.txt \
	CMakeLists.txt \
	src/CMakeLists.txt


